apiVersion: v1
kind: Pod
metadata:
  labels:
    threatfeed: snort
  name: tf-ubuntu
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - command:
        - sleep
        - '3600'
      image: ubuntu
      name: test